import { Platform, StatusBar, StyleSheet } from 'react-native';
import { fontFamilies } from './fonts';

const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight || 0 : 0;
const topBarPadding = Math.max(statusBarHeight - 8, 0);

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F5F7',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingTop: topBarPadding,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#D8DCE2',
  },
  greeting: {
    flex: 1,
    marginLeft: 12,
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2A37',
    fontFamily: fontFamilies.medium,
  },
  bell: {
    fontSize: 22,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  calorieCard: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  calorieMetric: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  calorieContext: {
    marginTop: 6,
    fontSize: 14,
    color: '#6B7280',
    fontFamily: fontFamilies.medium,
  },
  calorieValue: {
    fontSize: 48,
    fontWeight: '700',
    textAlign: 'center',
    color: '#1F2A37',
    fontFamily: fontFamilies.bold,
  },
  calorieUnit: {
    fontSize: 18,
    textAlign: 'center',
    color: '#4CAF50',
    marginBottom: 4,
    fontFamily: fontFamilies.medium,
  },
  stepText: {
    textAlign: 'left',
    color: '#6B7280',
    fontFamily: fontFamilies.regular,
  },
  stepRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepIcon: {
    marginRight: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2A37',
    marginBottom: 12,
    fontFamily: fontFamilies.medium,
  },
  macroBlock: {
    marginBottom: 12,
  },
  macroLabel: {
    fontSize: 14,
    color: '#1F2A37',
    marginBottom: 6,
    fontFamily: fontFamilies.regular,
  },
  progressBackground: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  waterProgressFill: {
    height: '100%',
    backgroundColor: '#90AEFF',
  },
  waterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  waterIcon: {
    fontSize: 20,
  },
  waterCupButton: {
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waterCupIcon: {
    fontSize: 28,
  },
  waterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  waterAmount: {
    fontSize: 24,
    fontWeight: '600',
    color: '#1F2A37',
    marginBottom: 6,
    fontFamily: fontFamilies.medium,
  },
  nextMeal: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mealIconPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  mealEmoji: {
    fontSize: 22,
  },
  mealTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2A37',
    fontFamily: fontFamilies.medium,
  },
  mealDesc: {
    fontSize: 14,
    color: '#4B5563',
    marginTop: 2,
    fontFamily: fontFamilies.regular,
  },
  mealTimeText: {
    marginTop: 4,
    color: '#9CA3AF',
    fontFamily: fontFamilies.regular,
  },
  nextMealActions: {
    marginTop: 16,
  },
  eatButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  eatButtonDisabled: {
    backgroundColor: '#A5D6A7',
  },
  eatButtonCompleted: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  eatButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontFamily: fontFamilies.medium,
  },
  eatButtonTextCompleted: {
    color: '#1F2A37',
  },
  waterAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nextMealLink: {
    marginTop: 12,
    alignItems: 'center',
  },
  nextMealLinkText: {
    color: '#0EA5E9',
    fontFamily: fontFamilies.medium,
  },
  mealsContainer: {
    flex: 1,
    padding: 16,
    paddingBottom: 32,
  },
  mealsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  groceryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#ECFDF5',
    marginBottom: 16,
  },
  groceryButtonIcon: {
    marginRight: 6,
  },
  groceryButtonText: {
    color: '#047857',
    fontFamily: fontFamilies.medium,
  },
  logoEmoji: {
    fontSize: 28,
  },
  mealsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2A37',
    fontFamily: fontFamilies.bold,
  },
  mealsSubtitle: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
    fontFamily: fontFamilies.regular,
  },
  mealsAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#D8DCE2',
  },
  dayScroll: {
    marginBottom: 16,
    maxHeight: 100,
  },
  daySelector: {
    paddingHorizontal: 8,
  },
  dayPill: {
    minWidth: 80,
    height: 60,
    paddingHorizontal: 18,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5E7EB',
    marginRight: 12,
  },
  dayPillSelected: {
    backgroundColor: '#D1FAE5',
    borderWidth: 1,
    borderColor: '#4ADE80',
  },
  dayText: {
    color: '#1F2937',
    fontWeight: '600',
    fontFamily: fontFamilies.medium,
  },
  dayTextSelected: {
    color: '#047857',
    fontFamily: fontFamilies.medium,
  },
  mealCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#fff',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    position: 'relative',
  },
  mealCardExpanded: {
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  mealIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  mealPhotoThumbWrapper: {
    marginRight: 12,
    borderRadius: 8,
    overflow: 'hidden',
    width: 60,
    height: 60,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  mealPhotoThumb: {
    width: '100%',
    height: '100%',
  },
  mealCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mealInfo: {
    flex: 1,
  },
  mealHeader: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2A37',
    fontFamily: fontFamilies.medium,
  },
  mealSubtleText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: fontFamilies.regular,
    marginTop: 2,
  },
  expandIndicator: {
    fontSize: 22,
    color: '#1F2A37',
    fontFamily: fontFamilies.medium,
    marginLeft: 8,
  },
  mealDetails: {
    marginTop: 12,
    paddingLeft: 54,
  },
  mealNote: {
    marginTop: 4,
    fontSize: 13,
    color: '#4CAF50',
    fontFamily: fontFamilies.medium,
  },
  checkBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#DCF7DC',
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBadgeText: {
    color: '#2E7D32',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: fontFamilies.bold,
  },
  requestButton: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    paddingVertical: 16,
    borderRadius: 28,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
  },
  requestButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: fontFamilies.medium,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F4F5F7',
  },
  placeholderText: {
    fontSize: 18,
    color: '#6B7280',
    fontFamily: fontFamilies.regular,
  },
  mealsList: {
    flex: 1,
  },
  mealsListContent: {
    paddingBottom: 120,
  },
  mealModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'flex-end',
  },
  mealModalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
    minHeight: '55%',
    maxHeight: '85%',
  },
  mealModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  mealModalTitle: {
    fontSize: 20,
    color: '#1F2A37',
    fontFamily: fontFamilies.bold,
  },
  mealModalSubtitle: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 2,
    fontFamily: fontFamilies.medium,
  },
  mealModalDesc: {
    color: '#1F2937',
    fontSize: 15,
    marginBottom: 16,
    fontFamily: fontFamilies.regular,
  },
  mealModalNote: {
    color: '#059669',
    fontSize: 13,
    fontFamily: fontFamilies.medium,
    marginBottom: 12,
  },
  mealModalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealModalBody: {
    flexGrow: 0,
  },
  mealModalSectionTitle: {
    fontSize: 15,
    color: '#111827',
    fontFamily: fontFamilies.semiBold,
    marginBottom: 8,
    marginTop: 12,
  },
  mealModalListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  mealModalBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CAF50',
    marginRight: 8,
  },
  mealModalListText: {
    flex: 1,
    color: '#374151',
    fontSize: 14,
    fontFamily: fontFamilies.regular,
  },
  mealModalStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  mealModalStepIndex: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  mealModalStepIndexText: {
    color: '#0369A1',
    fontFamily: fontFamilies.medium,
  },
  groceryListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  groceryCheckbox: {
    marginRight: 12,
  },
  groceryListText: {
    flex: 1,
    color: '#1F2937',
    fontSize: 15,
    fontFamily: fontFamilies.medium,
  },
  groceryListTextChecked: {
    textDecorationLine: 'line-through',
    color: '#9CA3AF',
  },
  photoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  photoModalBody: {
    width: '100%',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#0B1320',
    padding: 8,
    alignItems: 'center',
  },
  photoModalImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
  },
  requestInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: '#1F2937',
    fontFamily: fontFamilies.regular,
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 20,
  },
  mealSelectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  mealSelectionBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  mealSelectionBtnActive: {
    backgroundColor: '#DCFCE7',
    borderColor: '#4ADE80',
  },
  mealSelectionText: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: fontFamilies.medium,
  },
  mealSelectionTextActive: {
    color: '#15803D',
    fontWeight: '600',
  },
  sendButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  sendButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: fontFamilies.medium,
  },
});

export default styles;
